### ISSUE TITLE
Unable to run main.py

### ISSUE THREAD

**Issue by luisegehaijing** [zoharri/MBRL2#1]
Hi,
when I try to rerun your experiment with the command: 

python main.py --exp_name 30_train_6_kde_dream --env_t
ype pointrobot_varibad \   --env_num_train_goals 30 --num_dream_envs 6

I have got the following error:

main.py: error: unrecognized arguments: --exp_name 30_train_6_kde_dream --env_type pointrobot_
varibad --num_dream_envs 6

I have also tried to run python main.py directly
And I got:
Seeding random, torch, numpy.
Note that due to parallel processing results will be similar but not identical. Use only one p
rocess and set --deterministic_execution to True if you want identical results (only recommend
ed for debugging).
logging under /home/research/g.luise/multi_policy2024/MBRL2-main/logs/logs_GridNavi-v0/varibad
_73__17:11_11:58:32
Traceback (most recent call last):
  File "main.py", line 177, in <module>
    main()
  File "main.py", line 172, in main
    learner = MetaLearner(args)
  File "/home/research/g.luise/multi_policy2024/MBRL2-main/metalearner.py", line 47, in __init
__
    if args.sample_random_envs is True:
AttributeError: 'Namespace' object has no attribute 'sample_random_envs'

**Comment by luisegehaijing** [comment]
i added arguments myself so the issue is solved... the configuration files are also not updated for varibad-dream, I guess maybe it's better to include those files as it will be confusing.

**Comment by luisegehaijing** [comment]
There is also a mismatch between env_type and env-type somewhere.
